services:
  - type: web
    name: doc-analyzer
    runtime: docker         
    region: oregon
    plan: free

    envVars:
      - key: GROQ_API_KEY
        sync: false

      - key: API_KEY
        sync: false

      - key: GOOGLE_CREDENTIALS_JSON
        sync: false

      - key: MC_RUNS
        value: "3"

      - key: MAX_TEXT_CHARS
        value: "6000"